# Generated by Django 4.1.13 on 2024-02-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=350)),
                ('userID', models.CharField(max_length=12, unique=True)),
                ('rewardPoints', models.IntegerField(default=0)),
            ],
        ),
    ]
