# Generated by Django 4.1.13 on 2024-02-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_user_name_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rewardPoints',
            field=models.IntegerField(),
        ),
    ]
