# Generated by Django 4.1.13 on 2024-02-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_user_rewardpoints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
