# Generated by Django 5.0.3 on 2024-03-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userAuth',
        ),
    ]
